resolver: lts-12.16

extra-deps:
  - git: https://github.com/meck/alfred-footman.git
    commit: b41de69471aaffe0de0d732f8018d4ec3c3cf76d
  - git: https://github.com/ndmitchell/hoogle.git
    commit: 825e66699b3e14c968d8c08bc1ec26006d6d8183
  # - ../alfred-footman/

ghc-options:
  "$locals": -fhide-source-paths

