resolver: lts-12.16

extra-deps:
  - git: https://github.com/meck/alfred-footman.git
    commit: 4b4973e4bd39bb21ea0939a7e37e71c9f92913e1
  # - ../alfred-footman/

ghc-options:
  "$locals": -fhide-source-paths

