resolver: nightly-2019-02-14

extra-deps:
  - git: https://github.com/meck/alfred-footman.git
    commit: f78be01443549fd0f43e74feed8f1b3168d29ef0
  # - ../alfred-footman/

ghc-options:
  "$locals": -fhide-source-paths

