resolver: nightly-2019-02-04

extra-deps:
  - git: https://github.com/meck/alfred-footman.git
    commit: b6631ccacfc1245ee03df75641ae7aa784486b55
  # - ../alfred-footman/

ghc-options:
  "$locals": -fhide-source-paths

